# Generated by Django 5.2.7 on 2025-11-10 18:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViewCountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('day', models.DateField(db_index=True, default=datetime.date(2025, 11, 10))),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_counter', to='posts.post')),
            ],
        ),
    ]
