# Generated by Django 5.2.7 on 2025-11-10 18:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postviewcountmodel_view_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviewcountmodel',
            name='day',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='postviewcountmodel',
            constraint=models.UniqueConstraint(fields=('post', 'view_user', 'day'), name='uniq_post_user_day'),
        ),
    ]
